#!/bin/bash
#SBATCH --job-name=vitern_llava_train  # Job name
#SBATCH --output=output.log            # Standard output log
#SBATCH --error=error.log              # Standard error log
#SBATCH --nodes=1             # define node
#SBATCH --gpus-per-node=2     # define gpu limmit in 1 node
#SBATCH --ntasks=1            # define number tasks
#SBATCH --cpus-per-task=24    # There are 24 CPU cores
#SBATCH --time=4-00:10:00     # Max running time = 10 minutes
#aSBATCH --mem=1000
#aSBATCH --mem-per-gpu=80000
#SBATCH --nodelist=node001

# Load necessary modules

nvidia-smi
source ~/.bashrc
conda env list
echo "Setup conda env"
conda create --name vintern_Llavva python=3.10 -y
module load shared conda
. $CONDAINIT
conda activate vintern_Llavva

ZIP_FILE="./data_store/data_chart.zip"

wget --no-check-certificate "https://drive.usercontent.google.com/download?id=1N6S051Rs-BBacJjTpVMqkcDMtLPy8y7X&confirm=t&uuid=0650bfcc-c71d-46f9-9f11-95ed30151f42" -O $ZIP_FILE

echo "Unzip data"
unzip $ZIP_FILE -d ./data_store/

# Update pip
pip install --upgrade pip
pip -q install setuptools==69.5.1


echo "Install torch"
pip install torch==2.0.1 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118

pip install huggingface_hub

echo "Install other dependencies"
pip -q install -e .
pip -q install -e ".[train]"
echo "Finished installing dependencies"
