#!/bin/bash
#SBATCH --job-name=test_slurm # define job name
#SBATCH --nodes=1             # define node
#SBATCH --gpus-per-node=1     # define gpu limmit in 1 node
#SBATCH --ntasks=1            # define number tasks
#SBATCH --cpus-per-task=24    # There are 24 CPU cores
#SBATCH --time=4-00:10:00     # Max running time = 10 minutes
#aSBATCH --mem=1000
#aSBATCH --mem-per-gpu=80000
#SBATCH --exclude=node00[2-3]
while true; do nvidia-smi > gpu_status.txt; sleep 5; done &
module load shared conda
. $CONDAINIT
conda activate gnn_deep
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
export WANDB_PROJECT='llava-internvit-stage2-sharegpt-qwen1.5-0.5b'
export HF_API_TOKEN="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"

#train stage
IMAGE_FOLDER="./data_store/images"
DATA_PATH='./data_store/'
IMAGE_TOWER='OpenGVLab/InternViT-300M-448px'

deepspeed moellava/train/train_xformers.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path Qwen/Qwen1.5-0.5B \
    --mm_projector_lr 0.0000125 \
    --moe_enable False\
    --version qwen \
    --data_path ${DATA_PATH}/viet_share_gpt_full.json \
                ${DATA_PATH}/chart_QA_train.json \
    --image_folder $IMAGE_FOLDER \
    --image_tower $IMAGE_TOWER \
    --image_projector_type mlp2x_gelu \
    --pretrain_mm_mlp_adapter ./pretrain-intern-llava-qwen-05/mm_projector.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --fp16 True \
    --output_dir ./checkpoints/ft-stage2-internVit_llava_qwen1.5-0.5B-sharegpt_a100 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 8 \
    --lazy_preprocess True \
    --report_to tensorboard  \
    --push_to_hub True \
    --cache_dir ./cache_dir \
    --run_name ft-stage2-internVit_llava_qwen1.5-0.5B-sharegpt_a100 \


moe_mode="sparse"
num_experts=4
top_k_experts=2
use_residual=False
router_aux_loss_coef=0.01
MODEL_STAGE_2="./checkpoints/ft-stage2-internVit_llava_qwen1.5-0.5B-sharegpt_a100"

deepspeed moellava/train/train_mem.py \
    --moe_enable True --num_experts ${num_experts} --top_k_experts ${top_k_experts} --capacity_factor 1.5 \
    --moe_mode ${moe_mode} --use_residual ${use_residual} --router_aux_loss_coef ${router_aux_loss_coef} \
    --train_modules mlp.gate_proj mlp.up_proj mlp.down_proj wg \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path ${MODEL_STAGE_2} \
    --version qwen \
    --data_path ${DATA_PATH}/share_gpt_chartonly.json \
                ${DATA_PATH}/chart_QA_train_30percent.json \
    --image_folder $IMAGE_FOLDER \
    --image_tower $IMAGE_TOWER \
    --image_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --fp16 True \
    --output_dir ./checkpoints/MoE_LlaVa_Qwen1.5_0.5bx4Top2_VinTernVIT \
    --num_train_epochs 5 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-6 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to tensorboard \
    --push_to_hub True \
    --cache_dir ./cache_dir \
    --run_name moe-ft-stage3-llavaqwen1.5-0.5b-sharegpt_a100_VinternVIT \