#!/bin/bash
#SBATCH --job-name=test_slurm # define job name
#SBATCH --nodes=1             # define node
#SBATCH --gpus-per-node=1     # define gpu limmit in 1 node
#SBATCH --ntasks=1            # define number tasks
#SBATCH --cpus-per-task=24    # There are 24 CPU cores
#SBATCH --time=4-00:10:00     # Max running time = 10 minutes
#aSBATCH --mem=1000
#aSBATCH --mem-per-gpu=80000
#SBATCH --exclude=node00[2-3]
while true; do nvidia-smi > gpu_status.txt; sleep 5; done &
module load shared conda
. $CONDAINIT
conda activate gnn_deep
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
export WANDB_PROJECT='llava-internvit-stage2-sharegpt-qwen1.5-0.5b'

#train stage
IMAGE_FOLDER="./data_store/images"
DATA_PATH='./data_store/viet_share_gpt_5cd_shortversion.json'
IMAGE_TOWER='OpenGVLab/InternViT-300M-448px'

deepspeed moellava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path Qwen/Qwen1.5-0.5B \
    --mm_projector_lr 0.0000125 \
    --moe_enable False\
    --version qwen \
    --data_path $DATA_PATH \
    --image_folder $IMAGE_FOLDER \
    --image_tower $IMAGE_TOWER \
    --image_projector_type mlp2x_gelu \
    --pretrain_mm_mlp_adapter ./pretrain-intern-llava-qwen-05/mm_projector.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --fp16 True \
    --output_dir ./checkpoints/ft-stage2-internVit_llava_qwen1.5-0.5B-sharegpt \
    --num_train_epochs 5 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 2 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 8 \
    --lazy_preprocess True \
    --report_to wandb \
    --push_to_hub True \
    --cache_dir ./cache_dir \
    --run_name ft-stage2-internVit_llava_qwen1.5-0.5B-sharegpt \